/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dj_com_jni_demo1 */

#ifndef _Included_dj_com_jni_demo1
#define _Included_dj_com_jni_demo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dj_com_jni_demo1
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dj_com_jni_demo1_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
