/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dj_com_jni_demo2 */

#ifndef _Included_dj_com_jni_demo2
#define _Included_dj_com_jni_demo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dj_com_jni_demo2
 * Method:    getStringFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dj_com_jni_demo2_getStringFromNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dj_com_jni_demo2
 * Method:    getNumFromNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dj_com_jni_demo2_getNumFromNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
