/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dj_com_jni_GeoRela */

#ifndef _Included_dj_com_jni_GeoRela
#define _Included_dj_com_jni_GeoRela
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dj_com_jni_GeoRela
 * Method:    getStringFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dj_com_jni_GeoRela_getStringFromNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dj_com_jni_GeoRela
 * Method:    getNumFromNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dj_com_jni_GeoRela_getNumFromNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     dj_com_jni_GeoRela
 * Method:    equalPoints
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_dj_com_jni_GeoRela_equalPoints
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     dj_com_jni_GeoRela
 * Method:    online
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_dj_com_jni_GeoRela_online
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
